dist: xenial
language: cpp
compiler: clang
before_script:
  - sudo apt update
  - sudo apt install libboost-test-dev -y
  - sudo apt install doxygen -y
  - sudo apt install graphviz -y
addons:
  apt:
    packages:
      - doxygen
script:
  - doxygen Doxyfile
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package


deploy:
- provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GITHUB_TOKEN
  keep_history: true
   
- provider: script
  skip_cleanup: true
    
  script:
    - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ualexhamster:$BINTRAY_API_KEY "https://api.bintray.com/content/alexhamster/OTUS-Cpp/homework/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
    
