dist: xenial
language: cpp
compiler: clang
before_script:
  - sudo apt update
  - sudo apt install libboost-test-dev -y
  - sudo apt install doxygen

script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
  - doxygen Doxyfile
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master